# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md

max_width = 80
tab_spaces = 4

use_field_init_shorthand = true

reorder_imports = false
reorder_modules = false

match_block_trailing_comma = true

# nightly only
# force_multiline_blocks = true
# binop_separator = "Back"
# where_single_line = true
# format_strings = true
# indent_style = "Block"
# normalize_comments = true
# wrap_comments = true
